package converter

// embeddedCharMap contains the default Patris81 to Persian/Farsi character mapping
// This is embedded so the application works without requiring -c flag
// The * markers are replaced with [zwnj] for zero-width non-joiners
var embeddedCharMap = map[byte]string{
	0x90: "[?]",
	0x99: "ـ",
	0x9f: "ئ",
	0xa1: "ا",
	0xa2: "آ",
	0xa3: "ا",
	0xa4: "ب[zwnj]",
	0xa5: "ب",
	0xa6: "پ[zwnj]",
	0xa7: "پ",
	0xa8: "ت[zwnj]",
	0xa9: "ت",
	0xaa: "ث[zwnj]",
	0xab: "ث",
	0xac: "ج[zwnj]",
	0xad: "ج",
	0xae: "چ[zwnj]",
	0xaf: "چ",
	0xb0: "ح[zwnj]",
	0xb1: "ح",
	0xb2: "خ[zwnj]",
	0xb3: "خ",
	0xb4: "د",
	0xb5: "ذ",
	0xb6: "ر",
	0xb7: "ز",
	0xb8: "ژ",
	0xb9: "س[zwnj]",
	0xba: "س",
	0xbb: "ش[zwnj]",
	0xbc: "ش",
	0xbd: "ص[zwnj]",
	0xbe: "ص",
	0xbf: "ض[zwnj]",
	0xc0: "ض",
	0xc1: "ط",
	0xc2: "ظ",
	0xc3: "ع[zwnj]",
	0xc4: "ع[zwnj]",
	0xc5: "ع",
	0xc6: "ع",
	0xc7: "غ[zwnj]",
	0xc8: "غ[zwnj]",
	0xc9: "غ",
	0xca: "غ",
	0xcb: "ف[zwnj]",
	0xcc: "ف",
	0xcd: "ق[zwnj]",
	0xce: "ق",
	0xcf: "ک[zwnj]",
	0xd0: "ک",
	0xd1: "گ[zwnj]",
	0xd2: "گ",
	0xd3: "ل[zwnj]",
	0xd4: "ل",
	0xd5: "م[zwnj]",
	0xd6: "م",
	0xd7: "ن[zwnj]",
	0xd8: "ن",
	0xd9: "و",
	0xda: "ه[zwnj]",
	0xdb: "ه[zwnj]",
	0xdc: "ه",
	0xdd: "ه",
	0xde: "ی[zwnj]",
	0xdf: "ی[zwnj]",
	0xe0: "ی",
	0xf3: "0",
	0xf4: "1",
	0xf5: "2",
	0xf6: "3",
	0xf7: "4",
	0xf8: "5",
	0xf9: "6",
	0xfa: "7",
	0xfb: "8",
	0xfc: "9",
}

func init() {
	// Set the embedded mapping as default on package initialization
	// This ensures the application works even without -c flag
	SetDefaultMapping(embeddedCharMap)
}
